"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const Imagen_1 = require("../controllers/Imagen");
exports.imagen_router = express_1.Router();
var multiPart = require('connect-multiparty');
var multipartMiddleware = multiPart({ uploadDir: './imagenes' });
exports.imagen_router.post('/imagen/upload', multipartMiddleware, Imagen_1.subirImagen);
exports.imagen_router.delete('/imagen/:id_img', Imagen_1.eliminarImagen);
exports.imagen_router.get('/imagen/:id_img', Imagen_1.getImagenById);
exports.imagen_router.put('/imagen/:id_img', multipartMiddleware, Imagen_1.updateImagenById);
